name: wizlight
description: A dart package for controlling WiZ smart devices over UDP.
version: 2.0.0
homepage: https://github.com/sjhorn/wizlight
repository: https://github.com/sjhorn/wizlight

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
